---
- import_tasks: debian.yml
- name: User group present
  group:
    name: "{{ role_name }}"
    gid: "{{ users.scan }}"
    system: true
- name: User present
  user:
    name: "{{ role_name }}"
    comment: Scanner
    uid: "{{ users.scan }}"
    group: "{{ role_name }}"
    system: true
    create_home: false
    shell: "{{ user_shell }}"
- name: Root directory present
  file:
    dest: /srv/scan
    state: directory
    owner: "{{ role_name }}"
    mode: "u=rwx,g=rwx,o=x"
- name: Samba config present
  template:
    src: smb.conf
    dest: /etc/samba/
- name: Network access allowed
  firewalld:
    service: samba
    permanent: true
    state: enabled
