[global]
server role = standalone server
obey pam restrictions = yes
# This option controls how unsuccessful authentication attempts are mapped
# to anonymous connections
map to guest = bad user

########## Domains ###########
[scans]
comment = Scan inbox
valid users = scan
path = /srv/scan
create mask = 0660
writable = yes
browsable = yes

[media]
comment = Media
valid users = jellyfin
path = /srv/media
create mask = 0660
writable = yes
browsable = yes
