---
- import_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"
- name: SSH rate limiting active
  firewalld:
    rich_rule: 'rule family={{ item }} service name="ssh" log prefix="SSH rate limit" level="notice" accept limit value="30/h"'
    permanent: true
    state: enabled
  with_items:
    - ipv4
    - ipv6
- name: 2FA required
  community.general.pamd:
    name: cockpit
    type: auth
    control: optional
    module_path: pam_ssh_add.so
    new_type: auth
    new_control: required
    new_module_path: pam_google_authenticator.so
    state: after
