---
- name: Facts set
  ansible.builtin.set_fact:
    dir: "/opt/container/{{ role_name }}"
    id: "{{ users.cloud }}"
    volumes:
      zfs:
        - cloud
        - cloud-db
      local:
        - cloud-preview
- name: Import
  ansible.builtin.import_tasks: ../../shared/user/main.yml
- name: Import
  ansible.builtin.import_tasks: server.yml
  when: not is_backup_sink
- name: Import
  ansible.builtin.import_tasks: ../../shared/backup-sink/main.yml
  when: is_backup_sink
