---
- name: Sanoid config
  community.general.ini_file:
    path: "/etc/sanoid/sanoid.conf"
    section: "data/{{ role_name }}"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ opts | dict2items }}"
  vars:
    opts:
      use_template: production
      pre_snapshot_script: "/usr/local/bin/pg_dump.fish"
