---
- name: Facts set
  set_fact:
    pool_dir: "/srv/de.dm-poepperl.cloud"
    id: "{{ users.cloud }}"
    dir: "/opt/container/{{ role_name }}"
    volumes:
      zfs:
        - cloud-db
        - cloud
      local:
        - cloud-preview
- import_tasks: files.yml
- import_tasks: volumes.yml
- import_tasks: service.yml
