---
- name: DB user present
  community.postgresql.postgresql_user:
    login_user: root
    db: postgres
    name: "{{ role_name }}"
- name: Database present
  community.postgresql.postgresql_db:
    login_user: root
    name: "{{ role_name }}"
    owner: "{{ role_name }}"
