---
- name: Debian PHP packages present
  apt:
    name:
      - php-apcu
      - php-bcmath
      - php-curl
      - php-fpm
      - php-gd
      - php-gmp
      - php-imagick
      - php-intl
      - php-mbstring
      - php-pgsql
      - php-xml
      - php-zip
    install_recommends: no
