---
- name: Volumes
  block:
    - name: ZFS dataset present
      community.general.zfs:
        name: "data/{{ item | replace('-', '/') }}"
        state: present
        extra_zfs_properties:
          mountpoint: "legacy"
      loop: "{{ volumes.zfs }}"
    - name: ZFS volumes
      containers.podman.podman_volume:
        name: "{{ item }}"
        options:
          - "device=data/{{ item | replace('-', '/') }}"
          - "type=zfs"
      loop: "{{ volumes.zfs }}"
    - name: Local volumes
      containers.podman.podman_volume:
        name: "{{ item }}"
      loop: "{{ volumes.local }}"
