repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
        files: (\.ya?ml|\.butane)$
      - id: sort-simple-yaml
        files: ^roles/requirements\.yml$
  - repo: local
    hooks:
      - id: ansible-lint
        name: Ansible Lint local
        entry: ansible-lint
        language: system
        types: [yaml]
      - id: nft-lint
        name: nftables syntax check
        entry: python3 .github/scripts/nft-lint.py
        language: system
        files: (\.nft|defaults/main\.yml)$
        pass_filenames: false
