---
- name: Web serving hosts
  remote_user: root
  hosts:
    - homeserver
    - monitor.fritz.box
  roles:
    - caddy
    - container
- name: Pihole
  remote_user: root
  hosts:
    - monitor.fritz.box
  roles:
    - pihole
- name: Common headless functionality present
  hosts: headless
  remote_user: root
  roles:
    - apt
    - common
    - vim
    - system-mails
    - lid-switch
    - docs
    - cloud
    - backup-base
    - home
    - vault
- name: Home server configured
  hosts: homeserver
  remote_user: root
  roles:
    - scan
    - media
    - db
