---
- name: Common headless functionality present
  hosts: headless
  serial: 1
  remote_user: dmp
  become: true
  vars_files:
    - secrets.yml
  roles:
    - common
    - zfspool
    - lid_switch
- name: Service providers
  hosts: homeserver
  serial: 1
  remote_user: root
  become: false
  vars_files:
    - secrets.yml
  roles:
    - extensions
    - container
    - home
