---
- name: Common headless functionality present
  hosts: headless
  remote_user: root
  roles:
    - apt
    - common
    - vim
    - backup_base
- name: Pihole
  remote_user: root
  hosts:
    - pihole.lan
  roles:
    - pihole
- name: Service providers
  hosts: homeserver
  remote_user: root
  roles:
    - caddy
    - container
    - samba
    - nodered
    - home
    - cloud
    - docs
    - media
    - vault
