---
- name: Aptitude and unattented-upgrades installed
  ansible.builtin.apt:
    name:
      - aptitude
      - unattended-upgrades
    install_recommends: false

- name: Unattended Upgrades config file present
  ansible.builtin.template:
    src: unattended_upgrades.conf
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
