---
- name: Directory present
  ansible.builtin.file:
    path: "{{ dir }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"
- name: Build sources present
  notify: "monitor build changed"
  ansible.builtin.copy:
    src: src/
    dest: "{{ dir }}/src/"
    mode: "u=r,g=r,o=r"
- name: Caddyfile present
  ansible.builtin.template:
    src: Caddyfile
    dest: "/etc/caddy/avail/de.dm-poepperl.{{ role_name }}"
    mode: "u=r,g=r,o=r"
- name: Image builder present
  notify: "monitor build changed"
  ansible.builtin.template:
    src: build.fish
    dest: "{{ dir }}/build.fish"
    mode: "u=r,g=r,o=r"
- name: Deployment present
  notify: "monitor config changed"
  ansible.builtin.template:
    src: kube.yml.j2
    dest: "{{ dir }}/kube.yml"
    mode: "u=r,g=r,o=r"
- name: Firewall file present
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Icinga/icinga2/28e40ca/tools/firewalld/icinga2.xml
    dest: /etc/firewalld/services/icinga2.xml
    mode: "u=r,g=r,o=r"
