---
- name: Facts set
  ansible.builtin.set_fact:
    dir: "/opt/container/{{ role_name }}"
- name: Import
  ansible.builtin.import_tasks: files.yml
- name: Import
  ansible.builtin.import_tasks: service.yml
- name: Network access allowed
  ansible.posix.firewalld:
    service: icinga2
    permanent: true
    state: enabled
    immediate: true
