---
- name: Package installed
  ansible.builtin.apt:
    name: caddy
- name: Config file directories present
  ansible.builtin.file:
    state: directory
    dest: "/etc/caddy/{{ item }}"
    owner: root
    group: root
    mode: "u=rx,g=rx,o=rx"
  loop:
    - avail
    - sites
- name: Main Caddy file present
  notify: "caddy config changed"
  ansible.builtin.copy:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: "u=r,g=r,o=r"
