---
# https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
- name: UDP buffer size set
  ansible.posix.sysctl:
    name: "net.core.{{ item }}"
    value: 2500000
    sysctl_set: true
  loop:
    - wmem_max
    - rmem_max
- name: Package installed
  ansible.builtin.apt:
    name: caddy
- name: Config file directories present
  ansible.builtin.file:
    state: directory
    dest: "/etc/caddy/{{ item }}"
    owner: root
    group: root
    mode: "u=rx,g=rx,o=rx"
  loop:
    - avail
    - sites
- name: Main Caddy file present
  notify: "caddy config changed"
  ansible.builtin.copy:
    src: Caddyfile
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: "u=r,g=r,o=r"
- name: Network access allowed
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - http
    - http3
    - https
