[global]
server role = standalone server
# This option controls how unsuccessful authentication attempts are mapped
# to anonymous connections
map to guest = bad user

########## Domains ###########
[scans]
comment = Scan inbox
valid users = scan
path = /srv/scans
create mask = 0660
writable = yes
browsable = yes

[media]
comment = Jellyfin media collection
valid users = media
path = /srv/media
create mask = 0664
writable = yes
browsable = yes
