---
- name: Directory present
  ansible.builtin.file:
    path: "{{ dir }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"
- name: Build sources present
  notify: "samba build changed"
  ansible.builtin.copy:
    src: src/
    dest: "{{ dir }}/src/"
    mode: "u=r,g=r,o=r"
- name: Avahi service present
  notify: "avahi services changed"
  ansible.builtin.copy:
    src: samba.xml
    dest: /etc/avahi/services/samba.service
    mode: "u=r,g=r,o=r"
- name: Image builder present
  notify: "samba build changed"
  ansible.builtin.template:
    src: build.fish.j2
    dest: "{{ dir }}/build.fish"
    mode: "u=r,g=r,o=r"
- name: Deployment present
  notify: "samba config changed"
  ansible.builtin.template:
    src: kube.yml.j2
    dest: "{{ dir }}/kube.yml"
    mode: "u=r,g=r,o=r"
