---
- name: Facts set
  ansible.builtin.set_fact:
    dir: "/opt/container/{{ role_name }}"
- name: Debian packages present
  ansible.builtin.apt:
    name:
      - avahi-daemon
    install_recommends: false
- name: Import
  ansible.builtin.import_tasks: files.yml
- name: Import
  ansible.builtin.import_tasks: service.yml
- name: Network access allowed
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - samba
    - mdns
