---
- name: Directory present
  ansible.builtin.file:
    path: /etc/sanoid
    state: directory
    mode: "u=rwx,g=rx,o=rx"
- name: Sanoid config present
  ansible.builtin.template:
    src: sanoid.conf
    dest: /etc/sanoid/sanoid.conf
    owner: root
    group: root
    mode: "u=r,g=r,o=r"
