---
- name: User present
  ansible.builtin.user:
    name: "syncoid"
    home: "{{ syncoid_home }}"
    comment: "from Ansible"
    system: true
    shell: "/bin/sh"
- name: Pool imported
  ansible.builtin.command: "zpool import {{ dataset }}"
  changed_when: false
  register: backup_zpool
  failed_when: false
- name: Pool allowlist
  community.general.zfs_delegate_admin:
    users: syncoid
    name: "{{ dataset }}"
    permissions: "{{ 'compression,mountpoint,create,mount,receive,rollback,recordsize,destroy' if is_backup_sink else 'send,hold' }}"
- name: Srub timer enabled
  ansible.builtin.systemd_service:
    state: started
    name: "zfs-scrub-monthly@{{ dataset }}.timer"
- name: Sanoid timer enabled
  ansible.builtin.systemd_service:
    state: started
    name: sanoid.timer
- name: SELinux-compatible attributes on dataset
  become: true
  community.general.zfs:
    name: "{{ dataset }}"
    state: present
    extra_zfs_properties:
      xattr: "on" # or "sa" if supported
      acltype: posixacl
