---
- name: User present
  ansible.builtin.user:
    name: "{{ zfspool_syncoid_user }}"
    home: "{{ syncoid_home }}"
    comment: "from Ansible"
    system: true
    shell: "{{ zfspool_syncoid_shell }}"
- name: Import
  ansible.builtin.import_tasks: files.yml
- name: Pool imported
  block:
    - name: Pool import state
      ansible.builtin.command: "zpool list {{ dataset }}"
      changed_when: false
      check_mode: false
  rescue:
    - name: Pool import
      ansible.builtin.command: "zpool import {{ dataset }}"
      changed_when: true
- name: Pool allowlist
  community.general.zfs_delegate_admin:
    users: "{{ zfspool_syncoid_user }}"
    name: "{{ dataset }}"
    permissions: "{{ zfspool_permissions_sink if is_backup_sink else zfspool_permissions_source }}"
- name: Scrub timer enabled
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: "zfs-scrub-monthly@{{ dataset }}.timer"
- name: Sanoid timer enabled
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: sanoid.timer
- name: SELinux-compatible attributes on dataset
  become: true
  community.general.zfs:
    name: "{{ dataset }}"
    state: present
    extra_zfs_properties:
      xattr: "on" # or "sa" if supported
      acltype: posixacl
- name: Syncoid on backup system
  when: is_backup_sink
  ansible.builtin.import_tasks: syncoid.yml
- name: SELinux contexts for pool mounts
  when: not is_backup_sink
  ansible.builtin.import_tasks: selinux.yml
