---
- name: Unit files present
  ansible.builtin.copy:
    src: "syncoid@.{{ item }}"
    dest: /etc/systemd/system/
    mode: "ugo=r"
  loop:
    - timer
    - service
- name: Syncoid timer enabled
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    daemon_reload: true
    name: "syncoid@{{ item }}.timer"
  loop:
    - persist
    - media
