---
- name: DNS-over-TLS UCI changes committed
  listen: "dns over tls changed"
  community.openwrt.uci:
    command: commit
- name: Stubby restarted
  listen: "dns over tls changed"
  community.openwrt.service:
    name: stubby
    state: restarted
    enabled: true
- name: Dnsmasq reloaded
  listen: "dns over tls changed"
  community.openwrt.service:
    name: dnsmasq
    state: reloaded
