---
- import_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"
- name: Config file present
  no_log: true
  template:
    src: msmtp.conf
    dest: /etc/msmtprc
    owner: root
    group: root
    mode: "u=rw,g=r,o="
- name: Service file present
  copy:
    src: "notify-email@.service"
    dest: "/etc/systemd/system/notify-email@.service"
    owner: root
    group: root
    mode: "u=r,g=r,o=r"
- name: Mail script present
  template:
    src: "notify-email.py"
    dest: "/usr/local/bin/notify-email.py"
    owner: root
    group: root
    mode: "u=rx,g=r,o="
