---
- name: IPv6 ingress bridge units present
  notify: "dyndns systemd config changed"
  ansible.builtin.copy:
    src: "ingress6@.{{ item }}"
    dest: "/etc/systemd/system/ingress6@.{{ item }}"
    owner: root
    mode: "ugo=r"
  loop:
    - socket
    - service
- name: IPv6 ingress sockets active
  ansible.builtin.systemd_service:
    name: "ingress6@{{ item }}.socket"
    enabled: true
    state: started
    daemon_reload: true
  loop:
    - 443
    - 80
