---
- name: DynDNS updater script present
  ansible.builtin.copy:
    src: dyndns.fish
    dest: /usr/local/bin/dyndns.fish
    owner: root
    mode: "u=rwx,go=rx"
- name: DynDNS service present
  notify: "dyndns systemd config changed"
  ansible.builtin.template:
    src: dyndns.service
    dest: /etc/systemd/system/dyndns.service
    owner: root
    mode: "ugo=r"
- name: DynDNS timer present
  notify: "dyndns systemd config changed"
  ansible.builtin.copy:
    src: dyndns.timer
    dest: /etc/systemd/system/dyndns.timer
    owner: root
    mode: "ugo=r"
- name: DynDNS timer active
  ansible.builtin.systemd_service:
    name: dyndns.timer
    enabled: true
    state: started
    daemon_reload: true
