[{{ dataset }}/persist]
hourly = 36
daily = 30
monthly = 6
# Recursive cant't go into template!
recursive = true
use_template = default

[{{ dataset }}/media]
hourly = 6
daily = 3
monthly = 1
use_template = default

#############################
# templates below this line #
#############################

[template_default]
frequently = 0
yearly = 0
autoprune = true
autosnap = {{ (not is_backup_sink) | string | lower }}
