# Set default values for all following accounts.
defaults

auth on
tls on
tls_starttls off
tls_trust_file {{ ca_dir }}

account cloud
# Host name of the SMTP server
host smtp.strato.de
# Envelope-from address
from {{ mail_smtpname }}
# Authentication.
user {{ mail_smtpname }}
password {{ secrets.mails.pw | default('DUMMY') }}

# Set a default account
account default : cloud
