---
- name: Debian packages present
  ansible.builtin.apt:
    name:
      - podman
    install_recommends: false
- name: Directory present
  ansible.builtin.file:
    path: "/opt/container/"
    state: directory
    mode: "u=rwx,g=rx,o=rx"
- name: Unit files present
  ansible.builtin.copy:
    src: units/
    dest: /etc/systemd/system
    mode: "u=r,g=r,o=r"
