---
- name: Directory present
  ansible.builtin.file:
    path: "/opt/container/"
    state: directory
    mode: "u=rwx,g=rx,o=rx"
- name: Import
  ansible.builtin.import_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"
- name: Import
  ansible.builtin.import_tasks: systemd.yml
