---
- name: Debian packages present
  ansible.builtin.apt:
    name:
      - podman
      - buildah
      - catatonit
    install_recommends: false
- name: Unit files present
  ansible.builtin.copy:
    src: units/
    dest: /etc/systemd/system
    mode: "u=r,g=r,o=r"
