---
- name: Services confext synced
  ansible.builtin.command:
    cmd: fish sync.fish
    chdir: /var/mnt/ephemeral/services
  changed_when: false
- name: Upgrade timer active
  ansible.builtin.systemd_service:
    name: podman-auto-update.timer
    state: started
