---
- name: Sanoid config
  community.general.ini_file:
    path: "/etc/sanoid/sanoid.conf"
    section: "backup/{{ role_name }}"
    option: use_template
    mode: "u=r,g=r,o=r"
    value: production
- name: Syncoid pull service active
  ansible.builtin.systemd_service:
    name: "syncoid@{{ role_name }}.timer"
    state: started
    enabled: true
