---
- name: Firewalld service present
  ansible.builtin.copy:
    src: homekit.xml
    dest: /etc/firewalld/services
    mode: "ugo=r"
- name: Restart firewalld
  changed_when: false
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
- name: Udev rule present
  ansible.builtin.copy:
    src: conbee.rules
    dest: /etc/udev/rules.d
    mode: "ugo=r"
- name: Network access allowed
  ansible.posix.firewalld:
    service: '{{ item }}'
    permanent: true
    immediate: true
    state: enabled
  loop:
    - homekit
    - mdns
