---
- set_fact:
    container_name: nodered
- name: Service stopped
  systemd:
    state: stopped
    name: "container-{{ container_name }}"
  changed_when: false
  failed_when: false
- name: Container id file absent
  file:
    path: "/run/container-{{ container_name}}.ctr-id"
    state: absent
  changed_when: false
- name: Container present
  containers.podman.podman_container:
    image: "localhost/nodered"
    name: "{{ container_name }}"
    state: present
    network: host
    restart_policy: "no"
    volume:
      - "/srv/de.dm-poepperl.{{ container_name }}:/data"
    cidfile: "/run/container-{{ container_name }}.ctr-id"
    label:
      podman_systemd_unit: "container-{{ container_name }}.service"
      io.containers.autoupdate: local
    env:
      TZ: "Europe/Berlin"
- name: Service generated
  register: service
  when: not ansible_check_mode
  command:
    argv:
      - "/usr/bin/podman"
      - "generate"
      - "systemd"
      - "--name"
      - "--no-header"
      - "--new"
      - "{{ container_name }}"
- name: Service present
  when: not ansible_check_mode
  copy:
    content: "{{ service.stdout }}\n"
    dest: "/etc/systemd/system/container-{{ container_name}}.service"
- name: Service started
  systemd:
    state: started
    enabled: true
    name: "container-{{ container_name }}"
    daemon-reload: true
  changed_when: false
- name: Caddyfile present
  template:
    src: NodeCaddyfile
    dest: "/etc/caddy/avail/de.dm-poepperl.{{ container_name }}"
- name: System units present
  import_role:
    name: "0x0i.systemd"
  vars:
    unit_config:
      - name: "nodered-upgrade"
        Unit:
          Description: NodeRed upgrade
          Before: podman-auto-update.service
          After: network-online.target
          Requires: network-online.target
          OnFailure: notify-email@%N.service
        Service:
          WorkingDirectory: "/var/container-data/nodered"
          ExecStart: "/usr/bin/podman build --pull --tag nodered ."
          Type: oneshot
        Install:
          WantedBy: podman-auto-update.service
