---
- name: Service stopped
  ansible.builtin.systemd_service:
    state: stopped
    name: "container-{{ role_name }}"
  changed_when: false
  failed_when: false
- name: Container id file absent
  ansible.builtin.file:
    path: "/run/container-{{ role_name }}.ctr-id"
    state: absent
  changed_when: false
- name: Udev rules present
  ansible.builtin.copy:
    src: conbee.rules
    dest: /etc/udev.rules.d
    owner: root
    group: root
    mode: "u=r,g=r,o=r"
- name: Container present
  changed_when: false
  containers.podman.podman_container:
    image: "localhost/home-assistant"
    name: "{{ role_name }}"
    state: created
    network: host
    volume:
      - "/srv/de.dm-poepperl.{{ role_name }}:/config"
      - "/srv/media:/media"
    cidfile: "/run/container-{{ role_name }}.ctr-id"
    label:
      podman_systemd_unit: "container-{{ role_name }}.service"
      io.containers.autoupdate: local
    device: "/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2130827-if00:/dev/conbee"
- name: Service generated
  changed_when: false
  register: service
  when: not ansible_check_mode
  ansible.builtin.command:
    argv:
      - "/usr/bin/podman"
      - "generate"
      - "systemd"
      - "--name"
      - "--no-header"
      - "--new"
      - "{{ role_name }}"
- name: Service present
  when: not ansible_check_mode
  ansible.builtin.copy:
    content: "{{ service.stdout }}\n"
    dest: "/etc/systemd/system/container-{{ role_name }}.service"
    mode: "u=r,g=r,o=r"
- name: Service started
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: "container-{{ role_name }}"
    daemon-reload: true
  changed_when: false
- name: Caddyfile present
  ansible.builtin.template:
    src: Caddyfile
    dest: "/etc/caddy/avail/de.dm-poepperl.{{ role_name }}"
    mode: "u=r,g=r,o=r"
