---
- name: Import
  ansible.builtin.import_tasks: files.yml
- name: Import
  ansible.builtin.import_tasks: service.yml
- name: Import
  ansible.builtin.import_tasks: volumes.yml
- name: Network access allowed
  ansible.posix.firewalld:
    service: homekit
    permanent: true
    state: enabled
    immediate: true
