---
- name: Restart FPM
  listen: "fpm config changed"
  systemd:
    name: php-fpm
    state: restarted
- name: Restart web server
  listen: "web config changed"
  systemd:
    name: caddy
    state: restarted
