---
- name: Rebuild image
  listen: "cloud container config changed"
  systemd:
    name: "image-{{ role_name }}-upgrade"
    state: started
- name: Restart web server
  listen: "web config changed"
  systemd:
    name: caddy
    state: restarted
