---
- name: Restart deployment
  listen: "cloud config changed"
  systemd:
    name: "{{ service }}"
    state: restarted
- name: Rebuild image
  listen: "cloud build changed"
  notify: "cloud config changed"
  command:
    chdir: "/opt/container/{{ role_name }}"
    argv:
      - "/usr/bin/fish"
      - "build.fish"
- name: Restart web server
  listen: "web config changed"
  systemd:
    name: caddy
    state: restarted
