---
- name: Rebuild image
  listen: "docs build changed"
  notify: "docs config changed"
  ansible.builtin.systemd_service:
    name: "image-build@{{ role_name }}"
    state: started
- name: Restart deployment
  listen: "docs config changed"
  ansible.builtin.systemd_service:
    name: "{{ service }}"
    state: restarted
