---
- name: Pool imported
  ansible.builtin.command: zpool import backup
  changed_when: false
  register: zpool
  failed_when: false
- name: Pool allowlist
  community.general.zfs_delegate_admin:
    name: backup
    users: syncoid
    permissions: compression,mountpoint,create,mount,receive,rollback,destroy
