---
- name: Sanoid config
  community.general.ini_file:
    mode: "u=r,g=r,o=r"
    path: "/etc/sanoid/sanoid.conf"
    section: "template_production"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ opts | dict2items }}"
  vars:
    opts:
      frequently: 0
      hourly: 36
      daily: 30
      monthly: 6
      yearly: 3
      autosnap: "true"
      autoprune: "true"
      no_inconsistent_snapshot: "true"
      recursive: "true"
      script_timeout: 0
