---
- name: Debian packages present
  ansible.builtin.apt:
    name:
      - sanoid
      - python3-virtualenv
      - zfsutils-linux
    install_recommends: false
- name: Questionary present
  ansible.builtin.pip:
    name: questionary
    state: present
    virtualenv: /opt/rollback
    virtualenv_site_packages: true
- name: Import
  ansible.builtin.import_tasks: files.yml
- name: Import
  ansible.builtin.import_tasks: syncoid.yml
- name: Import
  ansible.builtin.import_tasks: backup.sink.yml
  when: is_backup_sink
- name: Import
  ansible.builtin.import_tasks: backup.source.yml
  when: not is_backup_sink
