---
- name: Set facts
  ansible.builtin.set_fact:
    ds: "{{ 'backup' if is_backup_sink else 'data' }}"
    permissions: "{{ 'compression,mountpoint,create,mount,receive,rollback,destroy' if is_backup_sink else 'send,hold' }}"
    autosnap: "{{ 'false' if is_backup_sink else 'true' }}"
- name: Debian packages present
  ansible.builtin.apt:
    name:
      - sanoid
      - python3-virtualenv
      - python3-pip
      - zfsutils-linux
    install_recommends: false
- name: Questionary present
  ansible.builtin.pip:
    name: questionary
    state: present
    virtualenv: /opt/rollback
    virtualenv_site_packages: true
- name: User present
  ansible.builtin.user:
    name: "syncoid"
    comment: "from Ansible"
    system: true
    shell: "/bin/sh"
- name: Import
  ansible.builtin.import_tasks: files.yml
- name: Pool imported
  ansible.builtin.command: "zpool import {{ ds }}"
  changed_when: false
  register: zpool
  failed_when: false
- name: Pool allowlist
  community.general.zfs_delegate_admin:
    users: syncoid
    name: "{{ ds }}"
    permissions: "{{ permissions }}"
- name: Syncoid on backup system
  when: is_backup_sink
  ansible.builtin.import_tasks: syncoid.yml
