---
- name: Unit files present
  ansible.builtin.copy:
    src: "syncoid@.{{ item }}"
    dest: /etc/systemd/system/
    mode: "u=r,g=r,o=r"
  loop:
    - timer
    - service
- name: Syncoid timer enabled
  ansible.builtin.systemd_service:
    state: enabled
    enabled: true
    daemon_reload: true
    name: "syncoid@{{ item }}.timer"
  loop:
    - data
    - media
