---
- name: logind.conf.d directory present
  become: true
  file:
    dest: /etc/systemd/logind.conf.d
    state: directory
    owner: root
    mode: "u=rx,g=rx,o=rx"
- name: Logind switch config present
  notify: "logind config changed"
  community.general.ini_file:
    path: "/etc/systemd/logind.conf.d/lid-switch.conf"
    section: Login
    option: HandleLidSwitch
    value: ignore
    owner: root
    mode: "u=rx,g=r,o=r"
