---
- name: Directory present
  ansible.builtin.file:
    path: "{{ dir }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"
- name: Deployment present
  notify: "vault config changed"
  ansible.builtin.template:
    src: kube.yml.j2
    dest: "{{ dir }}/kube.yml"
    mode: "u=r,g=r,o=r"
- name: Caddyfile present
  ansible.builtin.template:
    src: Caddyfile
    dest: "/etc/caddy/avail/de.dm-poepperl.{{ role_name }}"
    mode: "u=r,g=r,o=r"
