---
- name: User id set
  ansible.builtin.set_fact:
    id: "{{ users.vault }}"
    db_pw: "{{ secrets.vault.db_pw }}"
- name: Import
  ansible.builtin.import_tasks: ../../shared/user/main.yml
- name: Import
  ansible.builtin.import_tasks: server.yml
  when: not is_backup_sink
- name: Import
  ansible.builtin.import_tasks: ../../shared/backup-sink/main.yml
  when: is_backup_sink
