---
- name: Volumes
  block:
    - name: ZFS volumes
      containers.podman.podman_volume:
        name: '{{ item | replace("/", "-") }}'
        options:
          - "device=data/{{ item }}"
          - "type=zfs"
      loop:
        - vault
        - vault/db
    - name: Local volumes
      containers.podman.podman_volume:
        name: "{{ role_name }}-icons"
