---
- name: Rebuild image
  listen: "monitor build changed"
  notify: "monitor config changed"
  ansible.builtin.systemd_service:
    name: "image-build@{{ role_name }}"
    state: started
- name: Restart deployment
  listen: "monitor config changed"
  ansible.builtin.systemd_service:
    name: "{{ service }}"
    state: restarted
