---
dns_over_tls_transport: GETDNS_TRANSPORT_TLS
dns_over_tls_strict_auth: "1"

dns_over_tls_resolvers:
  - { name: quad9_a, address: "2620:fe::fe" }
  - { name: quad9_b, address: "2620:fe::9" }
dns_over_tls_tls_auth_name: dns.quad9.net
dns_over_tls_tls_port: "853"

dns_over_tls_stubby_listener: "127.0.0.1#5453"
