---
- name: Sanoid config
  community.general.ini_file:
    path: "/etc/sanoid/sanoid.conf"
    section: "template_backup"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ opts | dict2items }}"
  vars:
    opts:
      frequently: 0
      hourly: 0
      daily: 7
      monthly: 12
      yearly: 1
      autosnap: "false"
      autoprune: "true"
      hourly_warn: 2880
      hourly_crit: 3600
      daily_warn: 48
      daily_crit: 60
      recursive: "true"
- name: Syncoid Service - unit config
  community.general.ini_file:
    path: "/usr/local/lib/systemd/system/syncoid@.service"
    section: "Unit"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ opts | dict2items }}"
  vars:
    opts:
      After: network-online.target
      Requires: network-online.target
      On-Failure: network-online.target
- name: Syncoid Service - service config
  community.general.ini_file:
    path: "/usr/local/lib/systemd/system/syncoid@.service"
    section: "Service"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ opts | dict2items }}"
  vars:
    opts:
      User: backup
      Type: oneshot
      Restart: on-failure
      RestartSec: 5min
      ExecStart: /usr/sbin/syncoid --preserve-recordsize --recursive --no-sync-snap --no-privilege-elevation backup@dm-poepperl.de:data/%i backup/%i
- name: Syncoid Service - unit config
  community.general.ini_file:
    path: "/usr/local/lib/systemd/system/syncoid@.service"
    section: "Unit"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ opts | dict2items }}"
  vars:
    opts:
      After: network-online.target
      Requires: network-online.target
      On-Failure: network-online.target
- name: Syncoid Service - service config
  community.general.ini_file:
    path: "/usr/local/lib/systemd/system/syncoid@.service"
    section: "Service"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ opts | dict2items }}"
  vars:
    opts:
      User: backup
      Type: oneshot
      Restart: on-failure
      RestartSec: 5min
      ExecStart: /usr/sbin/syncoid --preserve-recordsize --recursive --no-sync-snap --no-privilege-elevation backup@dm-poepperl.de:data/%i backup/%i
- name: Syncoid Timer - timer config
  community.general.ini_file:
    path: "/usr/local/lib/systemd/system/syncoid@.timer"
    section: "Timer"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ opts | dict2items }}"
  vars:
    opts:
      OnCalendar: "12:00"
      Persistent: "true"
      Restart: on-failure
      RandomizedDelaySec: 30min
- name: Syncoid Timer - install config
  community.general.ini_file:
    path: "/usr/local/lib/systemd/system/syncoid@.timer"
    section: "Install"
    option: WantedBy
    value: default.target
