---
- name: Sanoid config
  community.general.ini_file:
    path: "/etc/sanoid/sanoid.conf"
    section: "template_production"
    option: "{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ opts | dict2items }}"
  vars:
    opts:
      frequently: 0
      hourly: 36
      daily: 30
      monthly: 6
      yearly: 3
      autosnap: "true"
      autoprune: "true"
      no_inconsistent_snapshot : "true"
      script_timeout: 0
- name: Postgre dump script present
  copy:
    src: pg_dump.fish
    dest: "/usr/local/bin/"
    owner: root
    group: root
    mode: "u=rx,g=rx,o=rx"
