---
- import_tasks: backup.debian.yml
- import_tasks: backup.sink.yml
  when: is_backup_sink
- import_tasks: backup.source.yml
  when: not is_backup_sink
- name: System units present
  import_role:
    name: "0x0i.systemd"
  vars:
    unit_config:
      - name: "override"
        type: conf
        path: "/etc/systemd/system/sanoid.service.d"
        Unit:
          OnFailure: "notify-email@%N.service"
