Unattended-Upgrade::Origins-Pattern {
        "origin=Debian";
        "origin=Ubuntu";
        "origin=Jellyfin";
        "origin=cloudsmith/caddy/stable";
};
Unattended-Upgrade::Mail "private@dm-poepperl.de";
Unattended-Upgrade::MailReport "only-on-error";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot {% if auto_reboot is true %}"true"{% else %}"false"{% endif %};
