Unattended-Upgrade::Origins-Pattern {
        "origin=*";
};
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade::Automatic-Reboot {% if auto_reboot is true %}"true"{% else %}"false"{% endif %};
