---
- name: Debian packages present
  apt:
    name:
      - fish
      - ripgrep
      - fd-find
      - aptitude
      - gnupg
      - exa
      - bat
      - smartmontools
    install_recommends: no
