---
- name: Debian packages present
  apt:
    name:
      - fish
      - ripgrep
      - fd-find
      - aptitude
      - gnupg
      - exa
      - bat
      - smartmontools
    install_recommends: no
- name: Debian packages absent
  apt:
    state: absent
    autoremove: true
    name:
      - rsyslog
      - snapd
      - modemmanager
      - pi-bluetooth
      - udisks2
- name: Services disabled
  systemd:
    state: stopped
    enabled: false
    name: "{{ item }}"
  loop:
    - cron
    - wpa_supplicant
