---
- name: Adneos systempub COPR repo present
  ansible.builtin.copy:
    src: copr-adneos-systempub.repo
    dest: /etc/yum.repos.d/copr-adneos-systempub.repo
    owner: root
    mode: "ugo=r"
- name: Systempub installed
  become: true
  community.general.rpm_ostree_pkg:
    name: systempub
    state: present
  notify: Layered package changed
- name: Fish shell installed
  become: true
  community.general.rpm_ostree_pkg:
    name: fish
    state: present
  notify: Layered package changed
- name: Fish config directory present
  ansible.builtin.file:
    dest: /etc/fish/conf.d
    state: directory
    owner: root
    mode: "u=rwx,go=rx"
- name: Shell environment present
  ansible.builtin.copy:
    src: config.fish
    dest: /etc/fish/conf.d/config.fish
    owner: root
    mode: "ugo=r"
- name: Interactive shells switch to fish
  ansible.builtin.copy:
    src: fishswitch.sh
    dest: /etc/profile.d/fishswitch.sh
    owner: root
    mode: "ugo=r"
- name: Services active
  ansible.builtin.systemd_service:
    name: "{{ item }}.service"
    enabled: true
    state: started
  loop:
    - tuned
    - systemd-oomd
- name: Auto upgrade
  ansible.builtin.import_tasks: autoupgrade.yml
