---
- name: Debian packages present
  apt:
    name:
      - fish
      - ripgrep
      - fd-find
      - gnupg
      - exa
      - bat
    install_recommends: no
- name: Fish config directory present
  become: true
  file:
    dest: /root/.config/fish
    state: directory
    owner: root
    mode: "u=rwx,g=rx,o=x"
- name: Shell environment templates for root present
  become: true
  copy:
    src: config.fish
    dest: /root/.config/fish/config.fish
    owner: root
    mode: "u=rw,g=,o="
- name: Fish is login shell for root
  become: true
  user:
    name: root
    shell: /usr/bin/fish
- import_tasks: pam.yml
