---
# https://developers.yubico.com/pam-u2f/
- name: U2F PAM module installed
  apt:
    name: libpam-u2f
    install_recommends: no
- name: U2F mapping path set
  set_fact:
    u2f_path: "/etc/u2f_mappings"
- name: U2F mapping set
  copy:
    src: u2f_mappings
    dest: "{{ u2f_path }}"
    owner: root
    group: root
    mode: "u=r,g=r,o="
- name: Able to login locally with security key
  community.general.pamd:
    name: login
    type: session
    control: required
    module_path: pam_env.so
    new_type: auth
    new_control: sufficient
    new_module_path: pam_u2f.so
    state: after
- name: Security key PAM options set
  community.general.pamd:
    name: login
    type: auth
    control: sufficient
    module_path: pam_u2f.so
    module_arguments: 'cue authfile={{ u2f_path }}'
    state: args_present
