---
- name: Services disabled
  ansible.builtin.systemd_service:
    state: stopped
    enabled: false
    name: "{{ item }}"
  loop:
    - multipathd
    - multipathd.socket
- name: Snaps absent
  community.general.snap:
    name: lxd
    state: absent
