---
- name: Services disabled
  ansible.builtin.systemd_service:
    state: stopped
    enabled: false
    masked: true
    name: "{{ item }}"
  loop:
    - multipathd
    - multipathd.socket
    - cron
- name: Ubuntu user absent
  ansible.builtin.user:
    name: ubuntu
    state: absent
    force: true
