---
- name: Services disabled
  ansible.builtin.systemd_service:
    state: stopped
    enabled: false
    masked: true
    name: "{{ item }}"
  loop:
    - multipathd
    - multipathd.socket
    - snapd
    - snapd.socket
    - cron
