---
- name: Directory present
  ansible.builtin.file:
    path: "{{ dir }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"
- name: Deployment present
  notify: "media config changed"
  ansible.builtin.template:
    src: kube.yml.j2
    dest: "{{ dir }}/kube.yml"
    mode: "u=r,g=r,o=r"
- name: Build file present
  notify: "media build changed"
  ansible.builtin.template:
    src: build.fish.j2
    dest: "{{ dir }}/build.fish"
    mode: "u=r,g=r,o=r"
- name: Caddyfile present
  ansible.builtin.template:
    src: Caddyfile
    dest: "/etc/caddy/avail/de.dm-poepperl.{{ role_name }}"
    mode: "u=r,g=r,o=r"
- name: Firewall file present
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jellyfin/jellyfin/master/fedora/jellyfin-firewalld.xml
    dest: /etc/firewalld/services/jellyfin.xml
    mode: "u=r,g=r,o=r"
