---
- name: Firewall file present
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/rpmfusion/jellyfin/master/jellyfin-firewalld.xml
    dest: /etc/firewalld/services/jellyfin.xml
    mode: "u=r,g=r,o=r"
- name: Network access allowed
  ansible.posix.firewalld:
    service: jellyfin
    permanent: true
    state: enabled
