---
- name: Facts set
  set_fact:
    dir: "/opt/container/{{ role_name }}"
- name: Directory present
  file:
    path: "{{ dir }}"
    state: directory
- name: Deployment present
  notify: "media config changed"
  template:
    src: kube.yml.j2
    dest: "{{ dir }}/kube.yml"
- name: Build file present
  notify: "media build changed"
  template:
    src: build.fish.j2
    dest: "{{ dir }}/build.fish"
- import_tasks: service.yml
- name: Volumes
  block:
    - name: ZFS volumes
      containers.podman.podman_volume:
        name: '{{ item | replace("/", "-")}}'
        options:
          - "device=data/{{ item }}"
          - "type=zfs"
      loop:
        - media
        - media/jellyfin
    - name: Local volumes
      containers.podman.podman_volume:
        name: "{{ role_name }}-cache"
- name: Caddyfile present
  template:
    src: Caddyfile
    dest: "/etc/caddy/avail/de.dm-poepperl.{{ role_name }}"
