---
- name: Dnsmasq ignores DHCP/resolv.conf-provided resolvers
  notify: "dns over tls changed"
  community.openwrt.uci:
    command: set
    key: "dhcp.@dnsmasq[0].noresolv"
    value: "1"

- name: Dnsmasq's only upstream is stubby
  notify: "dns over tls changed"
  community.openwrt.uci:
    command: set
    key: "dhcp.@dnsmasq[0].server"
    # dnsmasq's init script only reads `server` as a UCI list
    value:
      - "{{ dns_over_tls_stubby_listener }}"
