---
- name: DB user present
  community.postgresql.postgresql_user:
    login_user: root
    db: postgres
    name: "{{ role_name }}"
- name: Database present
  community.postgresql.postgresql_db:
    login_user: root
    name: "{{ role_name }}"
    owner: "{{ role_name }}"
- name: Network acces for database user allowed
  community.postgresql.postgresql_pg_hba:
    dest: "/etc/postgresql/{{ pgver }}/main/pg_hba.conf"
    contype: host
    users: "{{ role_name }}"
    address: samenet
    databases: samerole
    method: scram-sha-256
- name: Postgre network access allowed
  firewalld:
    service: postgresql
    permanent: true
    state: enabled
