---
- import_tasks: fedora.yml
  when: ansible_facts['distribution'] == "Fedora"
- import_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"
- name: Nvim config dir set
  set_fact:
        nvim_config_dir: .config/nvim
- name: /root/{{ nvim_config_dir }} directory present
  file:
    dest: /root/{{ nvim_config_dir }}
    state: directory
    owner: root
    mode: "u=rwx,g=rx,o=rx"
- name: Neovim config for root present
  copy:
    src: init.vim
    dest: /root/{{ nvim_config_dir }}
    owner: root
    mode: "u=rw,g=r,o=r"
- import_tasks: user.yml
  when: user is defined
