---
- name: Config directory for user present
  ansible.builtin.file:
    dest: /home/{{ user }}/{{ nvim_config_dir }}
    state: directory
    owner: "{{ user }}"
    mode: "u=rwx,g=rx,o=rx"
- name: Config for user present
  ansible.builtin.copy:
    src: init.vim
    dest: /home/{{ user }}/{{ nvim_config_dir }}
    owner: "{{ user }}"
    mode: "u=rw,g=r,o=r"
- name: Ideavim config for user present
  ansible.builtin.copy:
    src: ideavimrc.vim
    dest: /home/{{ user }}/.ideavimrc
    owner: "{{ user }}"
    mode: "u=rw,g=r,o=r"
