---
- name: Router
  hosts: router
  serial: 1
  remote_user: root
  become: false
  gather_facts: false
  roles:
    - router_wan
    - router_firewall
    - wireguard
    - homeserver_passthrough
    - dns_over_tls
    - router_lan
    - router_ddns
