---
- name: Common headless functionality present
  hosts: headless
  serial: 1
  remote_user: root
  become: false
  roles:
    - common
    - zfspool
    - lid_switch
- name: Service providers
  hosts: homeserver
  serial: 1
  remote_user: root
  become: false
  roles:
    - dyndns
    - container
    - home
