[{{ ds }}/persist]
hourly = 36
daily = 30
monthly = 6
use_template = default

[{{ ds }}/media]
hourly = 6
daily = 3
monthly = 1
use_template = default

#############################
# templates below this line #
#############################

[template_default]
frequently = 0
yearly = 0
autoprune = true
recursive = true
autosnap = {{ autosnap }}
