[{% if is_backup_sink is true %}"backup/"{% endif %}data]
use_template = production
recursive = true

[{% if is_backup_sink is true %}"backup/"{% endif %}data/media]
use_template = media
recursive = true

#############################
# templates below this line #
#############################

# name your templates template_templatename. you can create your own, and use them in your module definitions above.

[template_production]
frequently = 0
hourly = 36
daily = 30
monthly = 6
yearly = 0
script_timeout = 0
recursive = true
autoprune = true
autosnap = false
no_inconsistent_snapshot = true

[template_media]
hourly = 6
daily = 3
monthly = 1
yearly = 0
autoprune = true
autosnap = false
