[{% if is_backup_sink %}backup/{% endif %}data]
hourly = 36
daily = 30
monthly = 6
use_template = default
recursive = true

[{% if is_backup_sink %}backup/{% endif %}data/media]
hourly = 6
daily = 3
monthly = 1
use_template = default
recursive = true

#############################
# templates below this line #
#############################

[template_default]
frequently = 0
yearly = 0
autoprune = true
autosnap = {% if is_backup_sink %}false{% else %}true{% endif %}
