---
- name: Facts set
  ansible.builtin.set_fact:
    dir: "/opt/container/{{ role_name }}"
    volumes:
      zfs:
        - docs-db
        - docs
      local:
        - docs-redis
        - docs-thumbnails
        - docs-scan
- name: Import
  ansible.builtin.import_tasks: files.yml
- name: Import
  ansible.builtin.import_tasks: service.yml
- name: Import
  ansible.builtin.import_tasks: volumes.yml
