---
- name: Volumes
  block:
    - name: ZFS volumes
      containers.podman.podman_volume:
        name: "{{ item }}"
        options:
          - "device=data/{{ item | replace('-', '/') }}"
          - "type=zfs"
      loop: "{{ volumes.zfs }}"
    - name: Local volumes
      containers.podman.podman_volume:
        name: "{{ item }}"
      loop: "{{ volumes.local }}"
