---
- name: Network config present
  ansible.builtin.copy:
    src: 00-wired.network
    dest: /etc/systemd/network
    owner: root
    group: root
    mode: "u=r,g=r,o=r"
- name: Unbound config present
  notify: "unbound config changed"
  ansible.builtin.copy:
    src: unbound.conf
    dest: /etc/unbound/unbound.conf.d/pi-hole.conf
    owner: root
    group: root
    mode: "u=r,g=r,o=r"
- name: Pihole config present
  notify: "pihole config changed"
  ansible.builtin.template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
- name: EDNS config present
  notify: "pihole config changed"
  ansible.builtin.copy:
    content: "edns-packet-max=1232\n"
    dest: /etc/dnsmasq.d/99-edns.conf
    owner: root
    group: root
    mode: "u=r,g=r,o=r"
- name: Systemd units present
  ansible.builtin.copy:
    src: "pihole-up.{{ item }}"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: "u=r,g=r,o=r"
  loop:
    - service
    - timer
- name: Web index present
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/
    owner: root
    group: root
    mode: "u=r,g=r,o=r"
