---
- name: Unbound installed
  apt:
    name:
      - unbound
- name: Network config present
  copy:
    src: 00-wired.network
    dest: /etc/systemd/network
    owner: root
    group: root
    mode: "u=r,g=r,o=r"
- name: Unbound config present
  notify: "unbound config changed"
  copy:
    src: unbound.conf
    dest: /etc/unbound/unbound.conf.d/pi-hole.conf
    owner: root
    group: root
    mode: "u=r,g=r,o=r"
- name: Pihole config present
  notify: "pihole config changed"
  template:
    src: setupVars.conf.j2
    dest: /etc/pihole/setupVars.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
- name: EDNS config present
  notify: "pihole config changed"
  copy:
    content: "edns-packet-max=1232\n"
    dest: /etc/dnsmasq.d/99-edns.conf
    owner: root
    group: root
    mode: "u=r,g=r,o=r"
- name: Network access allowed
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - dhcp
    - http
    - dns
- name: Systemd units present
  copy:
    src: "pihole-up.{{ item }}"
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: "u=r,g=r,o=r"
  loop:
    - service
    - timer
- name: Systemd unit enabled
  systemd:
    name: pihole-up.timer
    enabled: true
    daemon-reload: true
- name: Service up
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - unbound
    - pihole-FTL
