---
- name: Unbound installed
  ansible.builtin.apt:
    name:
      - unbound
- name: Import
  ansible.builtin.import_tasks: files.yml
- name: Network access allowed
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - dhcp
    - http
    - dns
- name: Systemd unit enabled
  ansible.builtin.systemd_service:
    name: pihole-up.timer
    enabled: true
    daemon-reload: true
- name: Service up
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
  loop:
    - unbound
    - pihole-FTL
