---
- name: Restart deployment
  listen: "media config changed"
  systemd:
    name: "{{ service }}"
    state: restarted
- name: Rebuild image
  listen: "media build changed"
  notify: "media config changed"
  command:
    chdir: "/opt/container/{{ role_name }}"
    argv:
      - "/usr/bin/fish"
      - "build.fish"
